In [99]:
import pandas as pd
import numpy as np

In [100]:
df=pd.read_csv("messy_data.csv")

df
# print(df.head(30))

,Unnamed: 0,ID,Name,Age,Email,Join Date,Salary,Department
0,0,1e407ff9-6255-489d-a0de-34135d4f74bd,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.0000,Sales
1,1,379f55b8-87d5-4739-a146-7400b78c24d1,Jeremy Irwin,90.0,Jillian Jenkins,07-07-2022,139227.0000,NaN
2,2,18261368-dfa1-47f0-afc6-bddf45926b07,Jennifer Hammondquickly,66.0,jscottgreen.biz,21-11-2023,65550.0000,Engineering
3,3,ae7cf7cf-17cf-4c8b-9c44-4f61a9a238e5,Sydney Taylorso,39.0,luke56gonzalez.com,05-11-2021,139932.0000,SupportJ
4,4,14ed3e6a-e0f5-4bbe-8d93-8665267f5c90,Julia Lee,71.0,figueroakayla@yahoo.com,NaN,143456.0000,Marketing
...,...,...,...,...,...,...,...,...
10995,6523,07c223be-03e6-4f70-a2b5-86df778cc61a,NaN,NaN,NaN,NaN,NaN,NaN
10996,9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89gmail.com,24-06-2021,NaN,Sales
10997,7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Riossell,NaN,robert96@pollard-frye.com,15-08-2006,122609.5941,HR
10998,7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,roypark@warren.net,09-10-2020,147322.0052,Support
10999,7107,fc25a38a-5747-46eb-b6d3-7173f8255809,Caroline Ochoa,53.0,cdavis@hodges.com,10-08-2023,149224.0000,Support

In [101]:
# remove rows with no names

df.dropna(subset=["Name"],axis=0, inplace=True)

#  drop column ID

df=df.drop(columns=["ID"])

df.head(20)

,Unnamed: 0,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.00000,Sales
1,1,Jeremy Irwin,90.0,Jillian Jenkins,07-07-2022,139227.00000,NaN
2,2,Jennifer Hammondquickly,66.0,jscottgreen.biz,21-11-2023,65550.00000,Engineering
3,3,Sydney Taylorso,39.0,luke56gonzalez.com,05-11-2021,139932.00000,SupportJ
4,4,Julia Lee,71.0,figueroakayla@yahoo.com,NaN,143456.00000,Marketing
5,5,Lisa Bailey,81.0,milleryvonne@fowler-york.com,15-10-2016,123018.00000,SupportE
6,6,Patricia Brown DVM,66.0,pperkinshotmail.com,17-09-2020,77311.00000,HR
7,7,Derek Murphy,38.0,josephrobertsongmail.com,12-01-2021,NaN,Support
9,9,Jay Fisher,44.0,denisemaynard@jordan.com,08-12-2022,37701.72599,HR
10,10,Craig Conway,88.0,gerald47@woodard-smith.com,NaN,81214.52597,Engineering
11,11,Raymond Wilson,44.0,katherinewallacehotmail.com,26-08-2021,128335.00000,HRC
12,12,Amber Marsh,23.0,robert43@gmail.com,08-09-2023,112970.00000,Engineering
13,13,Patrick Mooney,57.0,bowersjasmine@hotmail.com,24-06-2023,41511.13965,SalesA
14,14,Nicole Cardenas,60.0,griffinlinda@harrison.com,16-10-2003,51625.81440,Marketing
16,16,Mark Wilkins,NaN,longjennifer@parker.biz,17-02-1991,85794.00000,SalesX
20,20,Eric Cole,NaN,Denise Martin,19-01-2022,60013.00000,Supportu
21,21,Danny Martinred,64.0,amyclements@lee.biz,30-08-2022,NaN,HR
22,22,Curtis Parkerlot,36.0,daniellewilliams@gmail.com,08-12-2023,NaN,HR
23,23,Laura Davis,60.0,garciaralph@hayes-hernandez.biz,06-10-1989,61209.00000,Engineeringi
25,25,Sharon Mcclure,25.0,mcmahonchristina@hotmail.com,09-06-2024,89208.00000,Marketing

In [102]:
df.isnull().sum()

Unnamed: 0      0
Name            0
Age           416
Email           0
Join Date     827
Salary        855
Department    883
dtype: int64

In [103]:
df.dtypes

Unnamed: 0      int64
Name           object
Age           float64
Email          object
Join Date      object
Salary        float64
Department     object
dtype: object

In [104]:
# Fill NaN Values
#-------------------------------------------------------
df['Age']=df['Age'].fillna(df['Age'].mode()[0])
df['Age']=df['Age'].astype(int)
df['Join Date']=df['Join Date'].fillna(df['Join Date'].mode()[0])
df['Salary']=df['Salary'].fillna(df['Salary'].mode()[0])
df['Salary']=df['Salary'].round(2)
df['Department']=df['Department'].fillna(df['Department'].mode()[0])
df.head(25)

,Unnamed: 0,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,88552.00,Sales
1,1,Jeremy Irwin,90,Jillian Jenkins,07-07-2022,139227.00,Support
2,2,Jennifer Hammondquickly,66,jscottgreen.biz,21-11-2023,65550.00,Engineering
3,3,Sydney Taylorso,39,luke56gonzalez.com,05-11-2021,139932.00,SupportJ
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,143456.00,Marketing
5,5,Lisa Bailey,81,milleryvonne@fowler-york.com,15-10-2016,123018.00,SupportE
6,6,Patricia Brown DVM,66,pperkinshotmail.com,17-09-2020,77311.00,HR
7,7,Derek Murphy,38,josephrobertsongmail.com,12-01-2021,96708.00,Support
9,9,Jay Fisher,44,denisemaynard@jordan.com,08-12-2022,37701.73,HR
10,10,Craig Conway,88,gerald47@woodard-smith.com,30-07-2021,81214.53,Engineering
11,11,Raymond Wilson,44,katherinewallacehotmail.com,26-08-2021,128335.00,HRC
12,12,Amber Marsh,23,robert43@gmail.com,08-09-2023,112970.00,Engineering
13,13,Patrick Mooney,57,bowersjasmine@hotmail.com,24-06-2023,41511.14,SalesA
14,14,Nicole Cardenas,60,griffinlinda@harrison.com,16-10-2003,51625.81,Marketing
16,16,Mark Wilkins,29,longjennifer@parker.biz,17-02-1991,85794.00,SalesX
20,20,Eric Cole,29,Denise Martin,19-01-2022,60013.00,Supportu
21,21,Danny Martinred,64,amyclements@lee.biz,30-08-2022,96708.00,HR
22,22,Curtis Parkerlot,36,daniellewilliams@gmail.com,08-12-2023,96708.00,HR
23,23,Laura Davis,60,garciaralph@hayes-hernandez.biz,06-10-1989,61209.00,Engineeringi
25,25,Sharon Mcclure,25,mcmahonchristina@hotmail.com,09-06-2024,89208.00,Marketing
26,26,Lori Hernandez,83,elizabeth22@yahoo.com,29-05-2021,52075.00,Engineering
27,27,Christina Norriscompare,84,haleygary@yahoo.com,17-07-2021,92668.00,Engineering
28,28,Amber Garcia,59,matthewvazquezhotmail.com,07-02-2020,96708.00,Engineering
29,29,Trevor Smith,30,robertflowers@diaz.biz,30-07-2021,133390.00,MarketingR
31,31,Mark Smith,64,rodney86fisher.com,30-07-2021,96708.00,SalesX

In [105]:
df.isnull().sum()

Unnamed: 0    0
Name          0
Age           0
Email         0
Join Date     0
Salary        0
Department    0
dtype: int64

In [106]:
# rename unnamed:0 to ID

df.rename(columns={'Unnamed: 0':'ID'},inplace=True)
df.head(20)
df

,ID,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,88552.00,Sales
1,1,Jeremy Irwin,90,Jillian Jenkins,07-07-2022,139227.00,Support
2,2,Jennifer Hammondquickly,66,jscottgreen.biz,21-11-2023,65550.00,Engineering
3,3,Sydney Taylorso,39,luke56gonzalez.com,05-11-2021,139932.00,SupportJ
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,143456.00,Marketing
...,...,...,...,...,...,...,...
10994,3978,Karen Wells,29,cheryllewis@hotmail.com,30-07-2021,147555.00,Engineering
10996,9785,Steven Armstrong,38,molly89gmail.com,24-06-2021,96708.00,Sales
10997,7826,Stephanie Riossell,29,robert96@pollard-frye.com,15-08-2006,122609.59,HR
10998,7648,Bonnie Benitez,37,roypark@warren.net,09-10-2020,147322.01,Support
10999,7107,Caroline Ochoa,53,cdavis@hodges.com,10-08-2023,149224.00,Support

In [107]:
# FORMAT EMAIL TO CORRECT FORMAT

import re



# Strip leading/trailing spaces and convert to lowercase
df['Email'] = df['Email'].str.strip().str.lower()

# Define a function to check email format, including missing domain
def validate_email(email):
    # Regular expression for valid email format
    email_regex = r'^[a-z0-9]+[.-_]*[a-z0-9]*@[a-z0-9.-]+\.[a-z]{2,}$'
    
    # Check if email matches the regex
    if re.match(email_regex, email):
        return email
    # Check if email has a missing domain (e.g., 'user@' or 'user@domain.')
    elif '.' in email and '@' not in email and not email.endswith("hotmail.com") and not email.endswith ("gmail.com"):
        username = email[:7] 
        domain = email[7:]    
        email = f"{username}@{domain}"
        return email
   
    elif not '@' in email and not re.search(r'@[a-z0-9.-]+\.[a-z]{2,}', email):
           
        if email.endswith("hotmail.com"):
            email= email.replace("hotmail.com","@hotmail.com")
            return email
        elif  email.endswith("gmail.com"):
          email= email.replace("gmail.com","@gmail.com")
          return email
        else:
            email=email.replace(" ","")
            return email+"@gmail.com"

    # else:
    #     return 'Invalid Email'

# Apply the email validation function
df['Email'] = df['Email'].apply(validate_email)

# Print the formatted DataFrame
df.head(30)

,ID,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,88552.00,Sales
1,1,Jeremy Irwin,90,jillianjenkins@gmail.com,07-07-2022,139227.00,Support
2,2,Jennifer Hammondquickly,66,jscottg@reen.biz,21-11-2023,65550.00,Engineering
3,3,Sydney Taylorso,39,luke56g@onzalez.com,05-11-2021,139932.00,SupportJ
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,143456.00,Marketing
5,5,Lisa Bailey,81,milleryvonne@fowler-york.com,15-10-2016,123018.00,SupportE
6,6,Patricia Brown DVM,66,pperkins@hotmail.com,17-09-2020,77311.00,HR
7,7,Derek Murphy,38,josephrobertson@gmail.com,12-01-2021,96708.00,Support
9,9,Jay Fisher,44,denisemaynard@jordan.com,08-12-2022,37701.73,HR
10,10,Craig Conway,88,gerald47@woodard-smith.com,30-07-2021,81214.53,Engineering
11,11,Raymond Wilson,44,katherinewallace@hotmail.com,26-08-2021,128335.00,HRC
12,12,Amber Marsh,23,robert43@gmail.com,08-09-2023,112970.00,Engineering
13,13,Patrick Mooney,57,bowersjasmine@hotmail.com,24-06-2023,41511.14,SalesA
14,14,Nicole Cardenas,60,griffinlinda@harrison.com,16-10-2003,51625.81,Marketing
16,16,Mark Wilkins,29,longjennifer@parker.biz,17-02-1991,85794.00,SalesX
20,20,Eric Cole,29,denisemartin@gmail.com,19-01-2022,60013.00,Supportu
21,21,Danny Martinred,64,amyclements@lee.biz,30-08-2022,96708.00,HR
22,22,Curtis Parkerlot,36,daniellewilliams@gmail.com,08-12-2023,96708.00,HR
23,23,Laura Davis,60,garciaralph@hayes-hernandez.biz,06-10-1989,61209.00,Engineeringi
25,25,Sharon Mcclure,25,mcmahonchristina@hotmail.com,09-06-2024,89208.00,Marketing
26,26,Lori Hernandez,83,elizabeth22@yahoo.com,29-05-2021,52075.00,Engineering
27,27,Christina Norriscompare,84,haleygary@yahoo.com,17-07-2021,92668.00,Engineering
28,28,Amber Garcia,59,matthewvazquez@hotmail.com,07-02-2020,96708.00,Engineering
29,29,Trevor Smith,30,robertflowers@diaz.biz,30-07-2021,133390.00,MarketingR
31,31,Mark Smith,64,rodney8@6fisher.com,30-07-2021,96708.00,SalesX
32,32,John Weeks,87,trobertson@gmail.com,13-06-2022,36554.00,Marketing
33,33,Jamie Valdez,73,cooperm@ichellefranklin.com,18-06-2021,96708.00,Sales
35,35,Ryan DanielsTV,35,hward@yahoo.com,14-01-2023,108317.00,Salesw
36,36,Veronica Schmidt,40,steven75@yahoo.com,13-03-2020,65482.00,Engineering
37,37,Richard Brooks,56,lukewalker@gmail.com,11-04-1997,116303.00,Sales

In [108]:
df['Department'].unique

<bound method Series.unique of 0              Sales
1            Support
2        Engineering
3           SupportJ
4          Marketing
            ...
10994    Engineering
10996          Sales
10997             HR
10998        Support
10999        Support
Name: Department, Length: 8667, dtype: object>

In [109]:
# CORRECT DEPARTMENT NAMES 

df.loc[df['Department'].str.startswith('Sales'), 'Department'] = 'Sales'
df.loc[df['Department'].str.startswith('Engineering'), 'Department'] = 'Engineering'
df.loc[df['Department'].str.startswith('Support'), 'Department'] = 'Support'
df.loc[df['Department'].str.startswith('HR'), 'Department'] = 'HR'
df.loc[df['Department'].str.startswith('Marketing'), 'Department'] = 'Marketing'


df.head(40)

,ID,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,88552.00,Sales
1,1,Jeremy Irwin,90,jillianjenkins@gmail.com,07-07-2022,139227.00,Support
2,2,Jennifer Hammondquickly,66,jscottg@reen.biz,21-11-2023,65550.00,Engineering
3,3,Sydney Taylorso,39,luke56g@onzalez.com,05-11-2021,139932.00,Support
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,143456.00,Marketing
5,5,Lisa Bailey,81,milleryvonne@fowler-york.com,15-10-2016,123018.00,Support
6,6,Patricia Brown DVM,66,pperkins@hotmail.com,17-09-2020,77311.00,HR
7,7,Derek Murphy,38,josephrobertson@gmail.com,12-01-2021,96708.00,Support
9,9,Jay Fisher,44,denisemaynard@jordan.com,08-12-2022,37701.73,HR
10,10,Craig Conway,88,gerald47@woodard-smith.com,30-07-2021,81214.53,Engineering
11,11,Raymond Wilson,44,katherinewallace@hotmail.com,26-08-2021,128335.00,HR
12,12,Amber Marsh,23,robert43@gmail.com,08-09-2023,112970.00,Engineering
13,13,Patrick Mooney,57,bowersjasmine@hotmail.com,24-06-2023,41511.14,Sales
14,14,Nicole Cardenas,60,griffinlinda@harrison.com,16-10-2003,51625.81,Marketing
16,16,Mark Wilkins,29,longjennifer@parker.biz,17-02-1991,85794.00,Sales
20,20,Eric Cole,29,denisemartin@gmail.com,19-01-2022,60013.00,Support
21,21,Danny Martinred,64,amyclements@lee.biz,30-08-2022,96708.00,HR
22,22,Curtis Parkerlot,36,daniellewilliams@gmail.com,08-12-2023,96708.00,HR
23,23,Laura Davis,60,garciaralph@hayes-hernandez.biz,06-10-1989,61209.00,Engineering
25,25,Sharon Mcclure,25,mcmahonchristina@hotmail.com,09-06-2024,89208.00,Marketing
26,26,Lori Hernandez,83,elizabeth22@yahoo.com,29-05-2021,52075.00,Engineering
27,27,Christina Norriscompare,84,haleygary@yahoo.com,17-07-2021,92668.00,Engineering
28,28,Amber Garcia,59,matthewvazquez@hotmail.com,07-02-2020,96708.00,Engineering
29,29,Trevor Smith,30,robertflowers@diaz.biz,30-07-2021,133390.00,Marketing
31,31,Mark Smith,64,rodney8@6fisher.com,30-07-2021,96708.00,Sales
32,32,John Weeks,87,trobertson@gmail.com,13-06-2022,36554.00,Marketing
33,33,Jamie Valdez,73,cooperm@ichellefranklin.com,18-06-2021,96708.00,Sales
35,35,Ryan DanielsTV,35,hward@yahoo.com,14-01-2023,108317.00,Sales
36,36,Veronica Schmidt,40,steven75@yahoo.com,13-03-2020,65482.00,Engineering
37,37,Richard Brooks,56,lukewalker@gmail.com,11-04-1997,116303.00,Sales
38,38,Cesar Morrison,72,lisa58@gmail.com,14-06-2020,162857.77,HR
39,39,Sandra Young,76,williamsummers@hotmail.com,30-06-2021,54014.00,Sales
41,41,Dawn Tucker,86,petersk@arenstafford.net,15-12-2019,118182.86,Engineering
42,42,Kayla Carpenter,61,dcooper@adams.net,08-06-2021,82857.40,Engineering
43,43,Laura Douglas,38,rebecca26@long-gray.org,15-01-2023,63299.00,Marketing
44,44,Evan Martinezimportant,34,tanyaglass@yahoo.com,01-01-2017,150059.40,Sales
45,45,William Avila,77,kevin62@smith.info,30-11-2022,118575.00,Sales
46,46,Kathleen Pitts,81,hgarcia@jackson.info,04-02-2019,114940.00,HR
47,47,Alice Lewis,20,juansalinas@hotmail.com,16-11-2020,163203.65,HR
49,49,Richard Collins,68,michaelhernandez@lee.com,12-05-2021,65728.00,Support

In [110]:
# Avoid duplicates
df_no_duplicates = df.drop_duplicates()
df.head(20)

,ID,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,88552.00,Sales
1,1,Jeremy Irwin,90,jillianjenkins@gmail.com,07-07-2022,139227.00,Support
2,2,Jennifer Hammondquickly,66,jscottg@reen.biz,21-11-2023,65550.00,Engineering
3,3,Sydney Taylorso,39,luke56g@onzalez.com,05-11-2021,139932.00,Support
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,143456.00,Marketing
5,5,Lisa Bailey,81,milleryvonne@fowler-york.com,15-10-2016,123018.00,Support
6,6,Patricia Brown DVM,66,pperkins@hotmail.com,17-09-2020,77311.00,HR
7,7,Derek Murphy,38,josephrobertson@gmail.com,12-01-2021,96708.00,Support
9,9,Jay Fisher,44,denisemaynard@jordan.com,08-12-2022,37701.73,HR
10,10,Craig Conway,88,gerald47@woodard-smith.com,30-07-2021,81214.53,Engineering
11,11,Raymond Wilson,44,katherinewallace@hotmail.com,26-08-2021,128335.00,HR
12,12,Amber Marsh,23,robert43@gmail.com,08-09-2023,112970.00,Engineering
13,13,Patrick Mooney,57,bowersjasmine@hotmail.com,24-06-2023,41511.14,Sales
14,14,Nicole Cardenas,60,griffinlinda@harrison.com,16-10-2003,51625.81,Marketing
16,16,Mark Wilkins,29,longjennifer@parker.biz,17-02-1991,85794.00,Sales
20,20,Eric Cole,29,denisemartin@gmail.com,19-01-2022,60013.00,Support
21,21,Danny Martinred,64,amyclements@lee.biz,30-08-2022,96708.00,HR
22,22,Curtis Parkerlot,36,daniellewilliams@gmail.com,08-12-2023,96708.00,HR
23,23,Laura Davis,60,garciaralph@hayes-hernandez.biz,06-10-1989,61209.00,Engineering
25,25,Sharon Mcclure,25,mcmahonchristina@hotmail.com,09-06-2024,89208.00,Marketing

In [111]:
df['Email'].unique

<bound method Series.unique of 0               xlopez@hotmail.com
1         jillianjenkins@gmail.com
2                 jscottg@reen.biz
3              luke56g@onzalez.com
4          figueroakayla@yahoo.com
                   ...
10994      cheryllewis@hotmail.com
10996            molly89@gmail.com
10997    robert96@pollard-frye.com
10998           roypark@warren.net
10999            cdavis@hodges.com
Name: Email, Length: 8667, dtype: object>

In [112]:
df['Join Date']=df['Join Date'].fillna(df['Join Date'].mode()[0])
df['Join Date'] = pd.to_datetime(df['Join Date'], dayfirst=True, errors='coerce')

# Format as 'DD/MM/YYYY' with '/'
df['Join Date'] = df['Join Date'].dt.strftime('%d-%m-%Y')

df.head(30)

,ID,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,88552.00,Sales
1,1,Jeremy Irwin,90,jillianjenkins@gmail.com,07-07-2022,139227.00,Support
2,2,Jennifer Hammondquickly,66,jscottg@reen.biz,21-11-2023,65550.00,Engineering
3,3,Sydney Taylorso,39,luke56g@onzalez.com,05-11-2021,139932.00,Support
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,143456.00,Marketing
5,5,Lisa Bailey,81,milleryvonne@fowler-york.com,15-10-2016,123018.00,Support
6,6,Patricia Brown DVM,66,pperkins@hotmail.com,17-09-2020,77311.00,HR
7,7,Derek Murphy,38,josephrobertson@gmail.com,12-01-2021,96708.00,Support
9,9,Jay Fisher,44,denisemaynard@jordan.com,08-12-2022,37701.73,HR
10,10,Craig Conway,88,gerald47@woodard-smith.com,30-07-2021,81214.53,Engineering
11,11,Raymond Wilson,44,katherinewallace@hotmail.com,26-08-2021,128335.00,HR
12,12,Amber Marsh,23,robert43@gmail.com,08-09-2023,112970.00,Engineering
13,13,Patrick Mooney,57,bowersjasmine@hotmail.com,24-06-2023,41511.14,Sales
14,14,Nicole Cardenas,60,griffinlinda@harrison.com,16-10-2003,51625.81,Marketing
16,16,Mark Wilkins,29,longjennifer@parker.biz,17-02-1991,85794.00,Sales
20,20,Eric Cole,29,denisemartin@gmail.com,19-01-2022,60013.00,Support
21,21,Danny Martinred,64,amyclements@lee.biz,30-08-2022,96708.00,HR
22,22,Curtis Parkerlot,36,daniellewilliams@gmail.com,08-12-2023,96708.00,HR
23,23,Laura Davis,60,garciaralph@hayes-hernandez.biz,06-10-1989,61209.00,Engineering
25,25,Sharon Mcclure,25,mcmahonchristina@hotmail.com,09-06-2024,89208.00,Marketing
26,26,Lori Hernandez,83,elizabeth22@yahoo.com,29-05-2021,52075.00,Engineering
27,27,Christina Norriscompare,84,haleygary@yahoo.com,17-07-2021,92668.00,Engineering
28,28,Amber Garcia,59,matthewvazquez@hotmail.com,07-02-2020,96708.00,Engineering
29,29,Trevor Smith,30,robertflowers@diaz.biz,30-07-2021,133390.00,Marketing
31,31,Mark Smith,64,rodney8@6fisher.com,30-07-2021,96708.00,Sales
32,32,John Weeks,87,trobertson@gmail.com,13-06-2022,36554.00,Marketing
33,33,Jamie Valdez,73,cooperm@ichellefranklin.com,18-06-2021,96708.00,Sales
35,35,Ryan DanielsTV,35,hward@yahoo.com,14-01-2023,108317.00,Sales
36,36,Veronica Schmidt,40,steven75@yahoo.com,13-03-2020,65482.00,Engineering
37,37,Richard Brooks,56,lukewalker@gmail.com,11-04-1997,116303.00,Sales

In [113]:
bins = [0, 50000, 100000, 150000]  # Salary ranges: 0-50k, 51k-100k, 101k-150k
labels = ['0-50k', '51k-100k', '101k-150k']  # Labels for each range

# Convert salary to fixed ranges using pd.cut
df['Salary'] = pd.cut(df['Salary'], bins=bins, labels=labels, right=False)
df.head(30)

,ID,Name,Age,Email,Join Date,Salary,Department
0,0,Hunter Thomas,25,xlopez@hotmail.com,30-07-2021,51k-100k,Sales
1,1,Jeremy Irwin,90,jillianjenkins@gmail.com,07-07-2022,101k-150k,Support
2,2,Jennifer Hammondquickly,66,jscottg@reen.biz,21-11-2023,51k-100k,Engineering
3,3,Sydney Taylorso,39,luke56g@onzalez.com,05-11-2021,101k-150k,Support
4,4,Julia Lee,71,figueroakayla@yahoo.com,30-07-2021,101k-150k,Marketing
5,5,Lisa Bailey,81,milleryvonne@fowler-york.com,15-10-2016,101k-150k,Support
6,6,Patricia Brown DVM,66,pperkins@hotmail.com,17-09-2020,51k-100k,HR
7,7,Derek Murphy,38,josephrobertson@gmail.com,12-01-2021,51k-100k,Support
9,9,Jay Fisher,44,denisemaynard@jordan.com,08-12-2022,0-50k,HR
10,10,Craig Conway,88,gerald47@woodard-smith.com,30-07-2021,51k-100k,Engineering
11,11,Raymond Wilson,44,katherinewallace@hotmail.com,26-08-2021,101k-150k,HR
12,12,Amber Marsh,23,robert43@gmail.com,08-09-2023,101k-150k,Engineering
13,13,Patrick Mooney,57,bowersjasmine@hotmail.com,24-06-2023,0-50k,Sales
14,14,Nicole Cardenas,60,griffinlinda@harrison.com,16-10-2003,51k-100k,Marketing
16,16,Mark Wilkins,29,longjennifer@parker.biz,17-02-1991,51k-100k,Sales
20,20,Eric Cole,29,denisemartin@gmail.com,19-01-2022,51k-100k,Support
21,21,Danny Martinred,64,amyclements@lee.biz,30-08-2022,51k-100k,HR
22,22,Curtis Parkerlot,36,daniellewilliams@gmail.com,08-12-2023,51k-100k,HR
23,23,Laura Davis,60,garciaralph@hayes-hernandez.biz,06-10-1989,51k-100k,Engineering
25,25,Sharon Mcclure,25,mcmahonchristina@hotmail.com,09-06-2024,51k-100k,Marketing
26,26,Lori Hernandez,83,elizabeth22@yahoo.com,29-05-2021,51k-100k,Engineering
27,27,Christina Norriscompare,84,haleygary@yahoo.com,17-07-2021,51k-100k,Engineering
28,28,Amber Garcia,59,matthewvazquez@hotmail.com,07-02-2020,51k-100k,Engineering
29,29,Trevor Smith,30,robertflowers@diaz.biz,30-07-2021,101k-150k,Marketing
31,31,Mark Smith,64,rodney8@6fisher.com,30-07-2021,51k-100k,Sales
32,32,John Weeks,87,trobertson@gmail.com,13-06-2022,0-50k,Marketing
33,33,Jamie Valdez,73,cooperm@ichellefranklin.com,18-06-2021,51k-100k,Sales
35,35,Ryan DanielsTV,35,hward@yahoo.com,14-01-2023,101k-150k,Sales
36,36,Veronica Schmidt,40,steven75@yahoo.com,13-03-2020,51k-100k,Engineering
37,37,Richard Brooks,56,lukewalker@gmail.com,11-04-1997,101k-150k,Sales

In [114]:
df.to_csv('cleaned_dataset.csv', index=False)